apiVersion: v1
kind: Secret
metadata:
  name: { { include "ssi-abstraction.fullname" . } }
  labels:
    app.kubernetes.io/name: { { include "ssi-abstraction.name" . } }
    helm.sh/chart: { { include "ssi-abstraction.chart" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/managed-by: { { .Release.Service } }
type: Opaque
data:
  AGENT_WALLET_KEY: M2NhZGZiNzNhYmQwYTEzZjM3NzA0NTI4YWI5Y2YzODY=
  AGENT_INDY_DID_SEED: NmI4Yjg4MmUyNjE4ZmE1ZDQ1ZWU3MjI5Y2EwMDAwMDA=
  AGENT_WALLET_STORAGE_CREDENTIALS_ACCOUNT: postgres
  AGENT_WALLET_STORAGE_CREDENTIALS_PASSWORD: postgres
  AGENT_WALLET_STORAGE_CREDENTIALS_ADMIN_ACCOUNT: postgres
  AGENT_WALLET_STORAGE_CREDENTIALS_ADMIN_PASSWORD: postgres
