name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    strategy:
      matrix:
        service: [connection-manager, credential-manager, did-manager, proof-manager, ssi-abstraction, schema-manager, tenant-manager]
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      build_args: SERVICE=${{ matrix.service }}
      service: ${{ matrix.service }}